apiVersion: v1
kind: Service
metadata:
  name: anticheat
  namespace: dgs
spec:
  selector:
    app: anticheat
  ports:
    - name: udp
      port: 42427
      targetPort: 42427
      protocol: UDP
    - name: tcp
      port: 42428
      targetPort: 42428
