apiVersion: v1
kind: Service
metadata:
  name: zone-node
  namespace: dgs
spec:
  type: NodePort
  selector:
    app: zone-node
  ports:
    - name: udp
      port: 42425
      targetPort: 42425
      protocol: UDP
      nodePort: 30425
