apiVersion: apps/v1
kind: Deployment
metadata:
  name: validador
  namespace: dgs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validador
  template:
    metadata:
      labels:
        app: validador
    spec:
      initContainers:
        - name: wait-head-server
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z head-server 42424; do echo waiting for head-server; sleep 2; done']
      containers:
        - name: validador
          image: dgs-validador-node:latest
          imagePullPolicy: Never
          env:
            - name: HEAD_SERVER_HOST
              value: "head-server"
            - name: HEAD_SERVER_PORT
              value: "42424"
            - name: PERSISTENCE_HOST
              value: "persistence"
            - name: PERSISTENCE_PORT
              value: "42429"
            - name: VALIDADOR_UDP_PORT
              value: "42427"
            - name: VALIDADOR_TCP_PORT
              value: "42428"
          ports:
            - containerPort: 42427
              protocol: UDP
            - containerPort: 42428
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
